### ISSUE TITLE
Problem with test run

### ISSUE THREAD

**Issue by jing-bi** [etaoxing/sgm-sorb#1]
Hi, thanks for the awesome implementation, really appreciate the effort.

However, when I try to run the base case. I got this problem:

```
Traceback (most recent call last):
  File "test/run_PointEnv.py", line 10, in <module>
    env = env_load_fn(cfg.env.env_name, cfg.env.max_episode_steps,
  File "test/pud/envs/simple_navigation_env.py", line 568, in env_load_fn
    env = PointEnv(walls=environment_name,
  File "test/pud/envs/simple_navigation_env.py", line 327, in __init__
    self.reset()
  File "test/pud/envs/simple_navigation_env.py", line 341, in reset
    self.state = self._sample_empty_state()
  File "test/pud/envs/simple_navigation_env.py", line 337, in _sample_empty_state
    assert not self._is_blocked(state)
AssertionError
```

Seems this is an environment problem, not sure how to solve it.

Thanks in advance for any help you can offer!

**Comment by jing-bi** [comment]
turns out the state data type is float64 which cannot be cast float32 defined in gym envs.
Change the dtype of spaces init will solve the problem
```
self.observation_space = gym.spaces.Box(
    low=np.array([0.0, 0.0]),
    high=np.array([self._height, self._width]),
    dtype=np.float64)
```
